version: '3'

services:
  autumnplains-server:
    container_name: autumnplains-server
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "4733:4733"
    networks:
      - autumn_network
    environment:
      - NODE_ENV=production
      - PORT=4733

networks:
  autumn_network:
    driver: bridge
