version: '3.8'

services:
  autumnplains-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: autumnplains-server
    container_name: autumnplains-server
    restart: unless-stopped
    ports:
      - "4733:4733"
    environment:
      - PORT=4733
