version: '3.8'

services:
  autumnplains-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: autumnplains-server
    container_name: autumnplains-server
    restart: unless-stopped
    ports:
      - "4733:4733"
    environment:
      - PORT=4733
      # Add other environment variables as needed
    # Uncomment to use volumes for persistent data
    # volumes:
    #   - ./data:/app/data
    
  # Optional: Add watchtower for automatic container updates
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 86400 # Check for updates once per day
    environment:
      - TZ=America/New_York # Set your timezone 